/* The code you provided is a Node.js application using Express framework to create a simple
server. Here's a breakdown of what each step is doing: */
// Step 1: Setup and Initialization
const express = require("express");
const morgan = require("morgan");

const app = express();
const port = 3000;

// Step 2: Middleware Development
const requestLogger = (req, res, next) => {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] ${req.method} ${req.url} - IP: ${req.ip}`);
  next();
};

// Step 3: Logging Details
app.use(morgan("combined"));

// Step 4: Global Middleware Inclusion
app.use(requestLogger);

app.get("/", (req, res) => {
  res.send("Hello, world!");
});

app.post("/data", (req, res) => {
  res.send("Data received.");
});

const debugLogger = (req, res, next) => {
  console.debug(
    `[DEBUG] ${req.method} ${req.url} - Headers: ${JSON.stringify(req.headers)}`
  );
  next();
};

// Include debug logger for specific routes (if needed)
app.use("/debug", debugLogger);

// Step 6: Start the server
app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});

// Step 7: Testing and Documentation
// Test the middleware by making GET and POST requests to the server
// Example: curl http://localhost:3000
// Observe logs generated by both the custom logger and Morgan
